language: python
python: '3.7'
sudo: required
dist: xenial
install: make requirements
script: make tox

addons:
  apt:
    sources:
      - sourceline: ppa:deadsnakes/ppa
    packages:
      - python3.4
      - python3.6
