language: python
python: '3.7'
sudo: required
dist: bionic
install: make requirements
script: make tox

addons:
  apt:
    sources:
      - sourceline: ppa:deadsnakes/ppa
    packages:
      - python3.4
      - python3.5
      - python3.8
      - python3-distutils
